theme: jekyll-theme-minimal
logo: https://static.vecteezy.com/system/resources/previews/014/635/724/non_2x/dna-strand-helix-science-genetic-genome-laboratory-technology-digital-futuristic-logo-design-vector.jpg
title: Na Bioinformatics (BIMM143, Fall 2024)
