theme: jekyll-theme-minimal
logo: https://image.similarpng.com/thumbnail/2021/06/Illustration-of-DNA,-genetic-symbol---people,-man-and-woman-icon-on-transparent-background-PNG.png
title: Na Bioinformatics (BIMM143, Fall 2024)
